### ISSUE TITLE
[Bug] keeps crashing every 5 seconds or so

### ISSUE THREAD

**Issue by Baka-6676** [Vendicated/Vencord#1119]
### Discord Account

spooky soap®#6676

### What happens when the bug or crash occurs?

it crashes when I even select another server or a dm
or go into user settings n shit

### What is the expected behaviour?

it just crashes

### How do you recreate this bug or crash?

random

### Errors

```
Routing/Utils] transitionTo - Transitioning to /channels/1095049221545132213/1095049221545132216
fd1f9ea7de3b25548016.js:5487 [Routing/Utils] transitionTo - Transitioning to /channels/1106917522760011806/1106917523791822861
fd1f9ea7de3b25548016.js:5487 [MessageActionCreators] Fetching messages for 1106919009728856196 between undefined and undefined. jump={"isHighlight":false,"jumpType":"ANIMATED"}
fd1f9ea7de3b25548016.js:5487 [MessageActionCreators] Fetched 0 messages from local database (channel_id: 1106919009728856196, remote_fetch_completed: false)
fd1f9ea7de3b25548016.js:5487 [Routing/Utils] transitionTo - Transitioning to /channels/1106917522760011806/1106919009728856196
fd1f9ea7de3b25548016.js:5487 [MessageActionCreators] Fetched 50 messages for 1106919009728856196 isBefore:false isAfter:false
fd1f9ea7de3b25548016.js:5487 [Routing/Utils] transitionTo - Transitioning to /channels/1106917522760011806/1106917523791822861
fd1f9ea7de3b25548016.js:5487 [Routing/Utils] transitionTo - Transitioning to /channels/1095049221545132213/1095049221545132216
fd1f9ea7de3b25548016.js:1787 TypeError: Cannot read properties of undefined (reading 'id')
    at Object.shouldShow (VencordWeb:18:572)
    at Object.wP (VencordWeb:177:28225)
    at eval (WebpackModule548625:2:1575)
    at S (WebpackModule548625:2:1743)
    at Sa (fd1f9ea7de3b25548016.js:1779:54)
    at gu (fd1f9ea7de3b25548016.js:1833:146)
    at Ic (fd1f9ea7de3b25548016.js:1826:89)
    at mc (fd1f9ea7de3b25548016.js:1826:17)
    at hc (fd1f9ea7de3b25548016.js:1825:867)
    at oc (fd1f9ea7de3b25548016.js:1822:642)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by pes18fan** [comment]
Experiencing the same issue.

**Comment by Vendicated** [comment]
Already fixed. If you're using Desktop/Firefox, just update

If you're using chromium (installed from https://chrome.google.com/webstore/detail/vencord-web/cbghhgpcnddeihccjmnadmkaejncjndb), you'll have to wait for google to approve the update which might take up to a few days 🤷🏻‍♂️

**Comment by Baka-6676** [comment]
Oh damn, thx though

**Comment by CodyMKW** [comment]
crashing for me as well when trying to open settings using the web version

**Comment by ItzOnlyAnimal** [comment]
read 2 comments above 💀

**Comment by Vendicated** [comment]
closing as the update has been pushed everywhere now. If you are still experiencing this issue it's because you're outdated, update!!
