### ISSUE TITLE
[Bug] Pfps and Server icons load incorrectly and media does not render

### ISSUE THREAD

**Issue by WhakEi** [Vendicated/Vencord#1259]
### Discord Account

WhakE#3365

### What happens when the bug or crash occurs?

Most server icons and pfps show up as pink, videos and pics don't render at all (audio does), this includes viewing image in full screen, however the magnification tool does load the zoomed version

### What is the expected behaviour?

I expect profile pictures to be round and not pinkified, and i expect images and videos to render instead of showing dark gray

### How do you recreate this bug or crash?

1. Install vencord
2. Turn on BetterFolders, CrashHandler, FakeNitro, and FakeProfileThemes

### Errors

```
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
```
and
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
UPDATE_VISIBLE_MESSAGES @ 31bb213ef464c72c8933.js:7300
(anonymous) @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9749
n @ 31bb213ef464c72c8933.js:9759
t._dispatch @ 31bb213ef464c72c8933.js:9760
(anonymous) @ 31bb213ef464c72c8933.js:9759
i.log @ 31bb213ef464c72c8933.js:9749
t._dispatchWithLogging @ 31bb213ef464c72c8933.js:9759
t._dispatchWithDevtools @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9758
t.flushWaitQueue @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9758
t.dispatch @ 31bb213ef464c72c8933.js:9758
A @ 31bb213ef464c72c8933.js:7288
E @ 31bb213ef464c72c8933.js:1217
I @ 31bb213ef464c72c8933.js:1218
y @ 31bb213ef464c72c8933.js:1217
setTimeout (async)
xo @ 31bb213ef464c72c8933.js:1212
h @ 31bb213ef464c72c8933.js:1217
T @ 31bb213ef464c72c8933.js:1218
t.setAutomaticAnchor @ WebpackModule584994:2
t.cleanAutomaticAnchor @ WebpackModule584994:2
handleScroll @ WebpackModule584994:2
eval @ WebpackModule584994:2
(anonymous) @ 31bb213ef464c72c8933.js:2811
t.stop @ 31bb213ef464c72c8933.js:2811
t.to @ 31bb213ef464c72c8933.js:2810
s @ 31bb213ef464c72c8933.js:2780
t.scrollTo @ WebpackModule584994:2
t.setScrollToBottom @ WebpackModule584994:2
t.restoreScroll @ WebpackModule584994:2
t.mergePropsAndUpdate_ @ WebpackModule584994:2
t.mergePropsAndUpdate @ WebpackModule584994:2
eval @ WebpackModule584994:2
ru @ 31bb213ef464c72c8933.js:1819
Tu @ 31bb213ef464c72c8933.js:1826
Iu @ 31bb213ef464c72c8933.js:1826
Iu @ 31bb213ef464c72c8933.js:1826
yu @ 31bb213ef464c72c8933.js:1826
(anonymous) @ 31bb213ef464c72c8933.js:1837
Oc @ 31bb213ef464c72c8933.js:1838
uc @ 31bb213ef464c72c8933.js:1832
Fi @ 31bb213ef464c72c8933.js:1771
(anonymous) @ 31bb213ef464c72c8933.js:1829
```
and also
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use our support channel please
