### ISSUE TITLE
[Bug] Invisible Chat crashes Vencord when encrypting links.

### ISSUE THREAD

**Issue by lovelydumpling** [Vendicated/Vencord#1306]
### Discord Account

lovelydumpling

### What happens when the bug or crash occurs?

Particularly when encrypting links that don't have an embed, such as direct links to files and some websites. 

If the link has an embed, such as a site preview or image, then it seems to work just fine. 

This happens both on Discord Stable and on Vencord Desktop. 

### What is the expected behaviour?

I expect the message to be decrypted and show the message with the link. 

### How do you recreate this bug or crash?

To reproduce, create a message where the Secret contains such a link. Simply http://example.com/ will work fine. Post the message. Upon decryption, Discord crashes and does not recover without manually quitting and restarting.

[Here is an example on the Vencord Discord, the decryption password is "password".](https://discord.com/channels/1015060230222131221/1024286218801926184/1119688925397667850)

### Errors

```
0034ebd72a91573d17ea.js:9191 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'url')
    at m (0034ebd72a91573d17ea.js:9191:990)
    at 0034ebd72a91573d17ea.js:6736:595
    at Array.map (<anonymous>)
    at w (0034ebd72a91573d17ea.js:6736:564)
    at x (0034ebd72a91573d17ea.js:6735:651)
    at 0034ebd72a91573d17ea.js:8120:859
    at t.update (0034ebd72a91573d17ea.js:4642:46)
    at MESSAGE_UPDATE (0034ebd72a91573d17ea.js:8120:823)
    at 0034ebd72a91573d17ea.js:9798:324
    at 0034ebd72a91573d17ea.js:9788:299
m @ 0034ebd72a91573d17ea.js:9191
(anonymous) @ 0034ebd72a91573d17ea.js:6736
w @ 0034ebd72a91573d17ea.js:6736
x @ 0034ebd72a91573d17ea.js:6735
(anonymous) @ 0034ebd72a91573d17ea.js:8120
t.update @ 0034ebd72a91573d17ea.js:4642
MESSAGE_UPDATE @ 0034ebd72a91573d17ea.js:8120
(anonymous) @ 0034ebd72a91573d17ea.js:9798
(anonymous) @ 0034ebd72a91573d17ea.js:9788
n @ 0034ebd72a91573d17ea.js:9798
t._dispatch @ 0034ebd72a91573d17ea.js:9798
(anonymous) @ 0034ebd72a91573d17ea.js:9797
i.log @ 0034ebd72a91573d17ea.js:9788
t._dispatchWithLogging @ 0034ebd72a91573d17ea.js:9797
t._dispatchWithDevtools @ 0034ebd72a91573d17ea.js:9797
(anonymous) @ 0034ebd72a91573d17ea.js:9797
t.flushWaitQueue @ 0034ebd72a91573d17ea.js:9797
(anonymous) @ 0034ebd72a91573d17ea.js:9797
t.dispatch @ 0034ebd72a91573d17ea.js:9796
updateMessage @ index.tsx:210
buildEmbed @ index.tsx:206
await in buildEmbed (async)
(anonymous) @ index.tsx:166
Promise.then (async)
onClick @ index.tsx:165
onClick @ WebpackModule584994:2
Me @ 0034ebd72a91573d17ea.js:1740
je @ 0034ebd72a91573d17ea.js:1740
(anonymous) @ 0034ebd72a91573d17ea.js:1761
Ur @ 0034ebd72a91573d17ea.js:1761
Gr @ 0034ebd72a91573d17ea.js:1761
(anonymous) @ 0034ebd72a91573d17ea.js:1767
cc @ 0034ebd72a91573d17ea.js:1832
Le @ 0034ebd72a91573d17ea.js:1739
Yr @ 0034ebd72a91573d17ea.js:1763
Kt @ 0034ebd72a91573d17ea.js:1746
Zt @ 0034ebd72a91573d17ea.js:1746
0034ebd72a91573d17ea.js:9961 TypeError: Cannot read properties of undefined (reading 'type')
    at eval (WebpackModule171771:2:153330)
    at Array.map (<anonymous>)
    at i.renderEmbeds (WebpackModule171771:2:153301)
    at i.render (WebpackModule171771:2:157367)
    at Ds (0034ebd72a91573d17ea.js:1803:100)
    at Rs (0034ebd72a91573d17ea.js:1802:890)
    at gu (0034ebd72a91573d17ea.js:1843:100)
    at Ic (0034ebd72a91573d17ea.js:1835:89)
    at mc (0034ebd72a91573d17ea.js:1835:17)
    at hc (0034ebd72a91573d17ea.js:1834:867)
r.<computed> @ 0034ebd72a91573d17ea.js:9961
ds @ 0034ebd72a91573d17ea.js:1796
Es.o.componentDidCatch.n.callback @ 0034ebd72a91573d17ea.js:1797
Bo @ 0034ebd72a91573d17ea.js:1778
Tu @ 0034ebd72a91573d17ea.js:1826
Iu @ 0034ebd72a91573d17ea.js:1826
yu @ 0034ebd72a91573d17ea.js:1826
(anonymous) @ 0034ebd72a91573d17ea.js:1837
Oc @ 0034ebd72a91573d17ea.js:1838
ic @ 0034ebd72a91573d17ea.js:1830
v @ 0034ebd72a91573d17ea.js:1952
C @ 0034ebd72a91573d17ea.js:1953
R.<computed> @ 3e4f363aa709b4c4e85d.js:67
D @ 3e4f363aa709b4c4e85d.js:66
A @ 3e4f363aa709b4c4e85d.js:66
0034ebd72a91573d17ea.js:9961 TypeError: Cannot read properties of undefined (reading 'type')
    at eval (WebpackModule171771:2:153330)
    at Array.map (<anonymous>)
    at i.renderEmbeds (WebpackModule171771:2:153301)
    at i.render (WebpackModule171771:2:157367)
    at Ds (0034ebd72a91573d17ea.js:1803:100)
    at Rs (0034ebd72a91573d17ea.js:1802:890)
    at gu (0034ebd72a91573d17ea.js:1843:100)
    at Ic (0034ebd72a91573d17ea.js:1835:89)
    at mc (0034ebd72a91573d17ea.js:1835:17)
    at hc (0034ebd72a91573d17ea.js:1834:867)
r.<computed> @ 0034ebd72a91573d17ea.js:9961
ds @ 0034ebd72a91573d17ea.js:1796
n.callback @ 0034ebd72a91573d17ea.js:1797
Bo @ 0034ebd72a91573d17ea.js:1778
Tu @ 0034ebd72a91573d17ea.js:1827
Iu @ 0034ebd72a91573d17ea.js:1826
yu @ 0034ebd72a91573d17ea.js:1826
(anonymous) @ 0034ebd72a91573d17ea.js:1837
Oc @ 0034ebd72a91573d17ea.js:1838
uc @ 0034ebd72a91573d17ea.js:1832
Fi @ 0034ebd72a91573d17ea.js:1771
(anonymous) @ 0034ebd72a91573d17ea.js:1838
Oc @ 0034ebd72a91573d17ea.js:1838
ic @ 0034ebd72a91573d17ea.js:1830
v @ 0034ebd72a91573d17ea.js:1952
C @ 0034ebd72a91573d17ea.js:1953
R.<computed> @ 3e4f363aa709b4c4e85d.js:67
D @ 3e4f363aa709b4c4e85d.js:66
A @ 3e4f363aa709b4c4e85d.js:66
0034ebd72a91573d17ea.js:1771 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at eval (WebpackModule171771:2:153330)
    at Array.map (<anonymous>)
    at i.renderEmbeds (WebpackModule171771:2:153301)
    at i.render (WebpackModule171771:2:157367)
    at Ds (0034ebd72a91573d17ea.js:1803:100)
    at Rs (0034ebd72a91573d17ea.js:1802:890)
    at gu (0034ebd72a91573d17ea.js:1843:100)
    at Ic (0034ebd72a91573d17ea.js:1835:89)
    at mc (0034ebd72a91573d17ea.js:1835:17)
    at hc (0034ebd72a91573d17ea.js:1834:867)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Fixed
