### ISSUE TITLE
[Bug] Discord crashes upon opening certain servers.

### ISSUE THREAD

**Issue by who-is-thiss** [Vendicated/Vencord#1436]
### Discord Account

who.is.thiss

### What happens when the bug or crash occurs?

Whenever I open some servers, for example, the Vencord server, Discord crashes with no explanation.

### What is the expected behaviour?

The server should open normally.

### How do you recreate this bug or crash?

1. Open the Vencord server

### Errors

These are the only red errors I found: 
```
86ca33085ef24bfc900a.js:10160 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Kr.<computed> [as get] (lazy.ts:49:50)
    at LockIcon (index.tsx:474:43)
    at Sa (WebpackModule364448:2:63050)
    at gu (WebpackModule364448:2:116108)
    at Ic (WebpackModule364448:2:109141)
    at mc (WebpackModule364448:2:109069)
    at hc (WebpackModule364448:2:108932)
    at oc (WebpackModule364448:2:105731)
    at uc (WebpackModule364448:2:106127)
r.<computed> @ 86ca33085ef24bfc900a.js:10160
overrideMethod @ react_devtools_backend.js:4026
ds @ WebpackModule364448:2
n.callback @ WebpackModule364448:2
Bo @ WebpackModule364448:2
Tu @ WebpackModule364448:2
Iu @ WebpackModule364448:2
yu @ WebpackModule364448:2
eval @ WebpackModule364448:2
Oc @ WebpackModule364448:2
uc @ WebpackModule364448:2
Fi @ WebpackModule364448:2
eval @ WebpackModule364448:2
Oc @ WebpackModule364448:2
ic @ WebpackModule364448:2
v @ 86ca33085ef24bfc900a.js:1943
C @ 86ca33085ef24bfc900a.js:1944
R.<computed> @ eb51f767f1c020ff66b9.js:67
D @ eb51f767f1c020ff66b9.js:66
A @ eb51f767f1c020ff66b9.js:66
WebpackModule364448:2 Uncaught TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Kr.<computed> [as get] (lazy.ts:49:50)
    at LockIcon (index.tsx:474:43)
    at Sa (WebpackModule364448:2:63050)
    at gu (WebpackModule364448:2:116108)
    at Ic (WebpackModule364448:2:109141)
    at mc (WebpackModule364448:2:109069)
    at hc (WebpackModule364448:2:108932)
    at oc (WebpackModule364448:2:105731)
    at uc (WebpackModule364448:2:106127)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by ActuallyTheSun** [comment]
update vencord
