### ISSUE TITLE
[Bug] MemberCount plugin crashes Discord when going to the "My Family" tab of Family Center

### ISSUE THREAD

**Issue by lumap** [Vendicated/Vencord#1453]
### Discord Account

lumap

### What happens when the bug or crash occurs?

This bug happens when going to the "My Family" tab of Family Center when you have a child added in your family

### What is the expected behaviour?

It doesn't crash

### How do you recreate this bug or crash?

1. Have your account's birthday set to 18 years or more 
2. Enable the MemberCount plugin
3. Go to User Settings -> Family Center -> My Family
4. Add a teen to your Family if you don't have any

### Errors

```js
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at eval (WebpackModule663866:2:6557)
    at Sa (cd2e09b83ca6fd0f2fbf.js:1784:54)
    at vs (cd2e09b83ca6fd0f2fbf.js:1794:281)
    at gu (cd2e09b83ca6fd0f2fbf.js:1840:210)
    at Ic (cd2e09b83ca6fd0f2fbf.js:1831:89)
    at mc (cd2e09b83ca6fd0f2fbf.js:1831:17)
    at hc (cd2e09b83ca6fd0f2fbf.js:1830:867)
    at oc (cd2e09b83ca6fd0f2fbf.js:1827:642)
    at uc (cd2e09b83ca6fd0f2fbf.js:1828:49)
    at Fi (cd2e09b83ca6fd0f2fbf.js:1767:577)```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
cannot repro with no kid added and i'm not able to set up one

pr would be appreciated

**Comment by lumap** [comment]
imma try to do a PR without crashing something else
