### ISSUE TITLE
When running the installer script in Wayland, it fails due to not recognizing X11

### ISSUE THREAD

**Issue by zoro11031** [Vendicated/Vencord#171]
```
2022/10/28 14:13:49 PlatformError: X11: Failed to open display :0
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x10004?})
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/error.go:174 +0x1d9
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/error.go:185
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0xc0004a5e68?, 0x6fb29a?)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/window.go:275 +0x3f
github.com/AllenDang/imgui-go.NewGLFW({0x31047c8?}, {0xa3b303, 0x11}, 0xac21b0?, 0x9dd740?, 0x0)
	/home/runner/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20220322114136-499bbf6a42ad/PlatformGlfw.go:68 +0xba
github.com/AllenDang/giu.NewMasterWindow({0xa3b303, 0x11}, 0x4b0, 0x320, 0xa0?)
	/home/runner/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:66 +0x10b
main.main()
	/home/runner/work/VencordInstaller/VencordInstaller/main.go:354 +0x75
```

**Comment by Vendicated** [comment]
Use XWayland

**Comment by Vendicated** [comment]
Or submit a pull request to add native wayland support

**Comment by Vendicated** [comment]
Actually it seems to support Wayland out of the box, could you try if this binary works on Wayland?

[VencordInstaller.zip](https://github.com/Vendicated/Vencord/files/9891404/VencordInstaller.zip)

or build from source via
```sh
go build --ldflags="-s -w -X 'main.InstallerGitHasha=$(git rev-parse --short HEAD)'" --tags wayland
```

**Comment by zoro11031** [comment]
Working right now so haven't tried everything, but the linked installer produced the same error. I will try running in XWayland next and then building from source
