### ISSUE TITLE
[Bug] webpack.ts undefined

### ISSUE THREAD

**Issue by ohitstom** [Vendicated/Vencord#1840]
### Discord Account

ohitstom

### What happens when the bug or crash occurs?

On discord startup, webpack.ts.

### What is the expected behaviour?

Webpack to be patched

### How do you recreate this bug or crash?

start discord check console

### Errors

```
Uncaught TypeError: Cannot read properties of undefined (reading 'c')
    at Bs (webpack.ts:66:18)
    at set (patchWebpack.ts:41:17)
    at 3c303a51c34bd0eb0192.js:1:111651
    at 3c303a51c34bd0eb0192.js:1:111746
    at 3c303a51c34bd0eb0192.js:1:112894
```
![image](https://github.com/Vendicated/Vencord/assets/22730962/dac4a007-cac8-4672-a58f-d0805d48368f)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by ohitstom** [comment]
updating vencord fixed this error, even though im not on canary.

**Comment by kilianMalherbe** [comment]
> ![image](https://user-images.githubusercontent.com/22730962/277923225-0e48dbe7-c0e0-41dd-8ba4-230ec6594e4c.png)

Happening on Vesktop 0.4.1

**Comment by FieryFlames** [comment]
👏 Update 👏 Vencord 👏

**Comment by ohitstom** [comment]
> 👏 Update 👏 Vencord 👏

reopened because @NYRI4 did update and the issue still is present.
