### ISSUE TITLE
[Bug] Vencord Web extension breaks several Discord pages

### ISSUE THREAD

**Issue by EDM115** [Vendicated/Vencord#1935]
### Discord Account

edm115

### What happens when the bug or crash occurs?

When you login from a new IP address, Discord sends you an email with a link (`https://discord.com/authorize-ip#token=...`)  
But the page simply never shows : 
![image](https://github.com/Vendicated/Vencord/assets/82015596/751178a6-7c92-47a4-ad9d-8ff262e6f1e5)
more details on the logs under :)

ALSO, Trying to use any invalid discord.com/invite/... link (and by extension discord.gg links) doesn't work (Vencord crash)

### What is the expected behaviour?

The Vencord Web plugin should not be enabled on those pages  
My workaround would be to fetch the url, and if it matches `https://discord.com/authorize-ip`, then the plugin should not try to edit the page

### How do you recreate this bug or crash?

1. Connect to another account after successfully being disconnected (not with QR Code, and I strongly believe that 2FA won't trigger IP link being sent)
2. Open the authorize link from your email
3. See that the page is just blank (content : https://nekobin.com/yanopuhave)
4. Disable the extension and reload the page (magic ! it works)

### Errors

I tried to space it, but here's screenshots for readability : https://telegra.ph/Bug-Vencord-Web-extension-disables-Discord-Authorize-IP-links-10-31

```
[FAST CONNECT] connecting to: wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream
authorize-ip:49
  
[FAST CONNECT] connected in 542ms
  
VencordWeb:5  Vencord   WebpackInterceptor  Patching webpackChunkdiscord_app.push

VencordWeb:5  Vencord   WebpackInterceptor  Found webpack module factory

135cb6938cf95f545311.js:1 [ProcessUtilsElectron] setMemoryInformation not available.

135cb6938cf95f545311.js:1 [default] [BUILD INFO] Release Channel: stable, Build Number: 241602, Version Hash: 86f279e5ab6276633caaa3b1a9e525eb78b2f7e3

135cb6938cf95f545311.js:1 AppCrashedFatalReport: getLastCrash not supported.

VencordWeb:5  Vencord   Webpack  Error: webpack.find found no module
    at As (VencordWeb:5:10329)
    at VencordWeb:12:935
    at VencordWeb:13:6156
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:133:38197)
    at Object.resolveGuildChannels (VencordWeb:133:38414)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a133c3866398a7796f2d.js:1:861151) Filter: [ƒ]
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
(anonymous) @ VencordWeb:12
(anonymous) @ VencordWeb:13
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
isHiddenChannel @ VencordWeb:133
resolveGuildChannels @ VencordWeb:133
getChannels @ WebpackModule923959:2
getDefaultChannel @ WebpackModule923959:2
G @ a133c3866398a7796f2d.js:1
getChannelId @ a133c3866398a7796f2d.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
iR @ WebpackModule435601:2
sW @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   Webpack  Error: webpack.find found no module
    at As (VencordWeb:5:10329)
    at VencordWeb:12:935
    at VencordWeb:13:6217
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:133:38197)
    at Object.resolveGuildChannels (VencordWeb:133:38414)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a133c3866398a7796f2d.js:1:861151) Filter: [ƒ]
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
(anonymous) @ VencordWeb:12
(anonymous) @ VencordWeb:13
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
isHiddenChannel @ VencordWeb:133
resolveGuildChannels @ VencordWeb:133
getChannels @ WebpackModule923959:2
getDefaultChannel @ WebpackModule923959:2
G @ a133c3866398a7796f2d.js:1
getChannelId @ a133c3866398a7796f2d.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
iR @ WebpackModule435601:2
sW @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

WebpackModule435601:2 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at bs.<computed> [as get] (VencordWeb:5:8661)
    at Object.isHiddenChannel (VencordWeb:133:38197)
    at Object.resolveGuildChannels (VencordWeb:133:38414)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a133c3866398a7796f2d.js:1:861151)
    at B.getChannelId (a133c3866398a7796f2d.js:1:863250)
    at d82268f01603c4109b3b.js:1:1249
    at d82268f01603c4109b3b.js:1:1591
o5 @ WebpackModule435601:2
o.componentDidCatch.n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   Webpack  Error: webpack.findByProps found no module
    at As (VencordWeb:5:10329)
    at vt (VencordWeb:5:10945)
    at VencordWeb:5:11001
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Object.handlePreventCrash (VencordWeb:48:2948)
    at Object.handleCrash (VencordWeb:48:2580)
    at M.triggerSoftCrash (WebpackModule967889:2:1262)
    at M.componentDidCatch (WebpackModule967889:2:1144)
    at o.componentDidCatch.n.callback (WebpackModule435601:2:70613) Filter: (2) ['pushLazy', 'popAll']0: "pushLazy"1: "popAll"length: 2[[Prototype]]: Array(0)
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
vt @ VencordWeb:5
(anonymous) @ VencordWeb:5
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
handlePreventCrash @ VencordWeb:48
handleCrash @ VencordWeb:48
triggerSoftCrash @ WebpackModule967889:2
componentDidCatch @ WebpackModule967889:2
o.componentDidCatch.n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   Webpack  Error: webpack.findByProps found no module
    at As (VencordWeb:5:10329)
    at vt (VencordWeb:5:10945)
    at VencordWeb:5:11001
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Hl (VencordWeb:13:8069)
    at Object.handlePreventCrash (VencordWeb:48:3014)
    at Object.handleCrash (VencordWeb:48:2580)
    at M.triggerSoftCrash (WebpackModule967889:2:1262)
    at M.componentDidCatch (WebpackModule967889:2:1144) Filter: ['openModalLazy']
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
vt @ VencordWeb:5
(anonymous) @ VencordWeb:5
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
Hl @ VencordWeb:13
handlePreventCrash @ VencordWeb:48
handleCrash @ VencordWeb:48
triggerSoftCrash @ WebpackModule967889:2
componentDidCatch @ WebpackModule967889:2
o.componentDidCatch.n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   Webpack  Error: webpack.find found no module
    at As (VencordWeb:5:10329)
    at VencordWeb:12:935
    at VencordWeb:13:6156
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:133:38197)
    at Object.resolveGuildChannels (VencordWeb:133:38414)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a133c3866398a7796f2d.js:1:861151) Filter: [ƒ]
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
(anonymous) @ VencordWeb:12
(anonymous) @ VencordWeb:13
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
isHiddenChannel @ VencordWeb:133
resolveGuildChannels @ VencordWeb:133
getChannels @ WebpackModule923959:2
getDefaultChannel @ WebpackModule923959:2
G @ a133c3866398a7796f2d.js:1
getChannelId @ a133c3866398a7796f2d.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
iR @ WebpackModule435601:2
sW @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   Webpack  Error: webpack.find found no module
    at As (VencordWeb:5:10329)
    at VencordWeb:12:935
    at VencordWeb:13:6217
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:133:38197)
    at Object.resolveGuildChannels (VencordWeb:133:38414)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a133c3866398a7796f2d.js:1:861151) Filter: [ƒ]
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
(anonymous) @ VencordWeb:12
(anonymous) @ VencordWeb:13
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
isHiddenChannel @ VencordWeb:133
resolveGuildChannels @ VencordWeb:133
getChannels @ WebpackModule923959:2
getDefaultChannel @ WebpackModule923959:2
G @ a133c3866398a7796f2d.js:1
getChannelId @ a133c3866398a7796f2d.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
(anonymous) @ d82268f01603c4109b3b.js:1
iR @ WebpackModule435601:2
sW @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

WebpackModule435601:2 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at bs.<computed> [as get] (VencordWeb:5:8661)
    at Object.isHiddenChannel (VencordWeb:133:38197)
    at Object.resolveGuildChannels (VencordWeb:133:38414)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a133c3866398a7796f2d.js:1:861151)
    at B.getChannelId (a133c3866398a7796f2d.js:1:863250)
    at d82268f01603c4109b3b.js:1:1249
    at d82268f01603c4109b3b.js:1:1591
o5 @ WebpackModule435601:2
n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   Webpack  Error: webpack.findByProps found no module
    at As (VencordWeb:5:10329)
    at vt (VencordWeb:5:10945)
    at VencordWeb:5:11001
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at bs.<computed> [as get] (VencordWeb:5:8667)
    at Yx (VencordWeb:18:14989)
    at Zx (VencordWeb:18:15036)
    at VencordWeb:18:15643 Filter: (2) ['createPortal', 'render']
_log @ VencordWeb:5
error @ VencordWeb:5
As @ VencordWeb:5
vt @ VencordWeb:5
(anonymous) @ VencordWeb:5
[vencord.lazy.get] @ VencordWeb:5
bs.<computed> @ VencordWeb:5
Yx @ VencordWeb:18
Zx @ VencordWeb:18
(anonymous) @ VencordWeb:18
Promise.then (async)
next @ VencordWeb:13
run @ VencordWeb:13
push @ VencordWeb:13
De @ VencordWeb:18
handlePreventCrash @ VencordWeb:48
handleCrash @ VencordWeb:48
triggerSoftCrash @ WebpackModule967889:2
componentDidCatch @ WebpackModule967889:2
o.componentDidCatch.n.callback @ WebpackModule435601:2
aK @ WebpackModule435601:2
iX @ WebpackModule435601:2
e @ WebpackModule435601:2
eval @ WebpackModule435601:2
sR @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

135cb6938cf95f545311.js:1 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 135cb6938cf95f545311.js:1:1334409
    at async Promise.all (index 3)
(anonymous) @ 135cb6938cf95f545311.js:1
Promise.then (async)
(anonymous) @ 135cb6938cf95f545311.js:1
iR @ WebpackModule435601:2
sW @ WebpackModule435601:2
sY @ WebpackModule435601:2
r3 @ WebpackModule435601:2
sE @ WebpackModule435601:2
emit @ 135cb6938cf95f545311.js:1
flushWaitQueue @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
dispatch @ 135cb6938cf95f545311.js:1
(anonymous) @ af942a733c169126d59d.js:1
Promise.then (async)
(anonymous) @ af942a733c169126d59d.js:1
(anonymous) @ 7f212d7b2214b392def0.js:1
c @ 7f212d7b2214b392def0.js:1
r @ 7f212d7b2214b392def0.js:1
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5 Uncaught (in promise) TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at bs.<computed> [as get] (VencordWeb:5:8661)
    at Yx (VencordWeb:18:14989)
    at Zx (VencordWeb:18:15036)
    at VencordWeb:18:15643
bs.<computed> @ VencordWeb:5
Yx @ VencordWeb:18
Zx @ VencordWeb:18
(anonymous) @ VencordWeb:18
postMessage (async)
n @ 7f212d7b2214b392def0.js:1
u.setImmediate @ 7f212d7b2214b392def0.js:1
R @ af942a733c169126d59d.js:1
G @ af942a733c169126d59d.js:1
initialize @ af942a733c169126d59d.js:1
initializeIfNeeded @ 135cb6938cf95f545311.js:1
(anonymous) @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
initialize @ 135cb6938cf95f545311.js:1
320777 @ 135cb6938cf95f545311.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
831881 @ 2182d33d74950f93eba0.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
r.O @ 2182d33d74950f93eba0.js:1
r.x @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1
(anonymous) @ 2182d33d74950f93eba0.js:1

VencordWeb:5  Vencord   WebpackInterceptor  Successfully initialised Vencord webpack
0cbd3f62b315bf33697e.js:1


0cbd3f62b315bf33697e.js:1 [DEPRECATED] Please use `subscribeWithSelector` middleware
o @ 0cbd3f62b315bf33697e.js:1
subscribe @ 0cbd3f62b315bf33697e.js:1
42963 @ c55e9a315d2967402244.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
926593 @ c55e9a315d2967402244.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
549869 @ c55e9a315d2967402244.js:1
BT.e.<computed> @ VencordWeb:175
r @ 2182d33d74950f93eba0.js:1
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
does this still happen? seems fixed for me

**Comment by Vendicated** [comment]
closing as solved, i will reopen if it's still an issue

**Comment by EDM115** [comment]
> does this still happen? seems fixed for me

it is indeed solved, after I reload the page  
I didn't opened an issue for that bug but it lasts since half a month : https://discord.com/channels/1015060230222131221/1026515880080842772/1187696426495528990
