### ISSUE TITLE
[Bug] Vencord Web extension breaks invalid Discord Invite links

### ISSUE THREAD

**Issue by EDM115** [Vendicated/Vencord#1952]
### Discord Account

edm115

### What happens when the bug or crash occurs?

Trying to use any invalid `discord.com/invite/...` link (and by extension `discord.gg` links) doesn't work (Vencord crash)  
![image](https://github.com/Vendicated/Vencord/assets/82015596/63109a4f-5d05-45f9-beae-498ac159267c)
same cause as #1935 ? idk  
Valid links works :  
![image](https://github.com/Vendicated/Vencord/assets/82015596/83fad673-ebc2-43c9-a03e-bf5c77dbf3e7)

### What is the expected behaviour?

It should show the invalid invite page  
![image](https://github.com/Vendicated/Vencord/assets/82015596/3f03d2aa-4455-454d-9527-470df460d194)

### How do you recreate this bug or crash?

1. Open any invalid invite link in a new tab
2. See that the page is just blank (content : https://nekobin.com/suwoxorebe)
3. Disable the extension and reload the page (magic ! it works)

### Errors

as usual, here are screenshots :) https://telegra.ph/Bug-Vencord-Web-extension-breaks-Discord-Invite-links-11-03

```
sandiction:49 [FAST CONNECT] connecting to: wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream

VencordWeb:5  Vencord   WebpackInterceptor  Patching webpackChunkdiscord_app.push

VencordWeb:5  Vencord   WebpackInterceptor  Patch by ViewIcons had no effect (Module id is 763866): /\{src:([A-Za-z_$][\w$]*)(?=,avatarDecoration)/
_log @ VencordWeb:5

sandiction:49 [FAST CONNECT] connected in 1953ms

VencordWeb:5  Vencord   WebpackInterceptor  Found webpack module factory

de2695c5b5cb94dae595.js:1 [ProcessUtilsElectron] setMemoryInformation not available.

de2695c5b5cb94dae595.js:1 [default] [BUILD INFO] Release Channel: stable, Build Number: 243588, Version Hash: 0168cc1e940f8d9bed72cfb7a418c43927eb1593

de2695c5b5cb94dae595.js:1 AppCrashedFatalReport: getLastCrash not supported.

VencordWeb:5  Vencord   Webpack  Error: webpack.find found no module
    at Ns (VencordWeb:5:10329)
    at VencordWeb:12:935
    at VencordWeb:13:6088
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at xs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:131:38455)
    at Object.resolveGuildChannels (VencordWeb:131:38672)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a9134718a1fbbf85a9ce.js:1:859949) Filter: Array(1)
_log @ VencordWeb:5

WebpackModule435601:2 TypeError: Cannot read properties of null (reading 'Permissions')
    at VencordWeb:13:6140
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at xs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:131:38455)
    at Object.resolveGuildChannels (VencordWeb:131:38672)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a9134718a1fbbf85a9ce.js:1:859949)
    at B.getChannelId (a9134718a1fbbf85a9ce.js:1:862048)
    at d82268f01603c4109b3b.js:1:1249
o5 @ WebpackModule435601:2

VencordWeb:5  Vencord   Webpack  Error: webpack.findByProps found no module
    at Ns (VencordWeb:5:10329)
    at at (VencordWeb:5:10945)
    at VencordWeb:5:11001
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at xs.<computed> [as get] (VencordWeb:5:8667)
    at Object.handlePreventCrash (VencordWeb:48:2948)
    at Object.handleCrash (VencordWeb:48:2580)
    at O.triggerSoftCrash (WebpackModule967889:2:1262)
    at O.componentDidCatch (WebpackModule967889:2:1144)
    at o.componentDidCatch.n.callback (WebpackModule435601:2:70613) Filter: Array(2)
_log @ VencordWeb:5

VencordWeb:5  Vencord   Webpack  Error: webpack.findByProps found no module
    at Ns (VencordWeb:5:10329)
    at at (VencordWeb:5:10945)
    at VencordWeb:5:11001
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at xs.<computed> [as get] (VencordWeb:5:8667)
    at zl (VencordWeb:13:7963)
    at Object.handlePreventCrash (VencordWeb:48:3014)
    at Object.handleCrash (VencordWeb:48:2580)
    at O.triggerSoftCrash (WebpackModule967889:2:1262)
    at O.componentDidCatch (WebpackModule967889:2:1144) Filter: Array(1)
_log @ VencordWeb:5

VencordWeb:5  Vencord   Webpack  Error: webpack.find found no module
    at Ns (VencordWeb:5:10329)
    at VencordWeb:12:935
    at VencordWeb:13:6088
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at xs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:131:38455)
    at Object.resolveGuildChannels (VencordWeb:131:38672)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a9134718a1fbbf85a9ce.js:1:859949) Filter: Array(1)
_log @ VencordWeb:5

WebpackModule435601:2 TypeError: Cannot read properties of null (reading 'Permissions')
    at VencordWeb:13:6140
    at [vencord.lazy.get] (VencordWeb:5:8193)
    at xs.<computed> [as get] (VencordWeb:5:8667)
    at Object.isHiddenChannel (VencordWeb:131:38455)
    at Object.resolveGuildChannels (VencordWeb:131:38672)
    at W.getChannels (WebpackModule923959:2:3158)
    at W.getDefaultChannel (WebpackModule923959:2:3281)
    at G (a9134718a1fbbf85a9ce.js:1:859949)
    at B.getChannelId (a9134718a1fbbf85a9ce.js:1:862048)
    at d82268f01603c4109b3b.js:1:1249
o5 @ WebpackModule435601:2

de2695c5b5cb94dae595.js:1 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at de2695c5b5cb94dae595.js:1:1336750
    at async Promise.all (index 3)

VencordWeb:5  Vencord   WebpackInterceptor  Successfully initialised Vencord webpack

VencordWeb:5  Vencord   WebpackInterceptor  Patch by MessageDecorationsAPI had no effect (Module id is 93332): /currentUserIsPremium:.{0,70}{children:[A-Za-z_$][\w$]*(?=}\))/
_log @ VencordWeb:5

VencordWeb:5  Vencord   WebpackInterceptor  Patch by ShowMeYourName had no effect (Module id is 93332): /(?<=onContextMenu:[A-Za-z_$][\w$]*,children:).*?\}/
_log @ VencordWeb:5

0cbd3f62b315bf33697e.js:1 [DEPRECATED] Please use `subscribeWithSelector` middleware
o @ 0cbd3f62b315bf33697e.js:1
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
closing this issue to track it in one single issue (since these issues are related), #1935
