### ISSUE TITLE
[Bug] TypeError: e.getTime is not a function

### ISSUE THREAD

**Issue by BerryGod1** [Vendicated/Vencord#2176]
### Discord Account

berrygod

### What happens when the bug or crash occurs?

When i open a locked channel and im using the review plugin
![image](https://github.com/Vendicated/Vencord/assets/108932405/1629eb55-aaa0-4dbf-a30b-4b4afad5b3de)
![image](https://github.com/Vendicated/Vencord/assets/108932405/2a1b0e6f-4835-49b3-9da3-d42d8c36ba1b)

### What is the expected behaviour?

When using the review plugin and opening a locked channel 
Tried reinstalling discord and vencord

### How do you recreate this bug or crash?

Open the profile or a locked channel

### Errors

When i view a locked channel
```
Component Stack 
    at d (https://discord.com/assets/f704fb87f8d9523e042e.js:1:9436)
    at r
    at div
    at Text (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:1181416)
    at div
    at div
    at zD (VencordRenderer:177:5646)
    at <anonymous> (VencordRenderer:14:12663)
    at r
    at div
    at div
    at e0 (WebpackModule533466:2:9457)
    at t (https://discord.com/assets/482.6e1c86f88a37a71d42ec.js:1:18714)
    at https://discord.com/assets/67690.949a40c153655ea7be23.js:1:2535
    at eval (WebpackModule533466:2:16852)
    at eA (WebpackModule252917:2:1972)
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:168995)
    at r (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1397755)
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:169683)
    at div
    at div
    at div
    at eF (WebpackModule252917:2:6851)
    at div
    at s (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:106554)
    at D (https://discord.com/assets/16962d52ef16eafca456.js:1:232322)
    at div
    at e (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:1402537)
    at y (https://discord.com/assets/16962d52ef16eafca456.js:1:232576)
    at x (https://discord.com/assets/16962d52ef16eafca456.js:1:233553)
    at div
    at u (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:186139)
    at https://discord.com/assets/16962d52ef16eafca456.js:1:217132
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:168995)
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:169683)
    at ts (https://discord.com/assets/16962d52ef16eafca456.js:1:62411)
    at Suspense
    at d
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:168995)
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:169683)
    at div
    at h (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:93111)
    at VerificationLayerProvider
    at c (https://discord.com/assets/44504.a24d96478100284b35e8.js:1:3718)
    at I (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1453736)
    at div
    at div
    at h (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:93111)
    at AppLayerProvider
    at A (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1390628)
    at M (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:198507)
    at _ (WebpackModule967889:2:2179)
    at S (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1462193)
    at N (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1462648)
    at T (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1651038)
    at l (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:89142)
    at p (https://discord.com/assets/807.7b5e740d7073c23a4a7b.js:1:10042)
    at d (https://discord.com/assets/48059.9715f43121fceb989b4e.js:1:49866)
    at c (https://discord.com/assets/807.7b5e740d7073c23a4a7b.js:1:52068)
    at eo (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1458869)
    at J (https://discord.com/assets/web.641f930748be695e4340.js:1:6396)
    at https://discord.com/assets/web.641f930748be695e4340.js:1:11782
    at T (https://discord.com/assets/62067.cb84b4617ec29dad30ac.js:1:1650229)
    at https://discord.com/assets/55695.1f3222e2a170c25c8fe1.js:1:235920
    at u (https://discord.com/assets/55695.1f3222e2a170c25c8fe1.js:1:229994)
    at f (https://discord.com/assets/41039.6d47c6ee08a5c558f08d.js:1:69600)
    at App
    at e (https://discord.com/assets/64999.3c0486790babc24c66a4.js:1:166277)
    at t (https://discord.com/assets/37248.e90e8800482fe6057ea8.js:1:858200)
    at o (https://discord.com/assets/web.641f930748be695e4340.js:1:37395)
    at d (https://discord.com/assets/48059.9715f43121fceb989b4e.js:1:49866)
    at c (https://discord.com/assets/807.7b5e740d7073c23a4a7b.js:1:52068)
```
And when i use the review plugin
```
A component threw an Error
 TypeError: e.getTime is not a function
    at u (41039.6d47c6ee08a5c558f08d.js:1:1043857)
    at c (41039.6d47c6ee08a5c558f08d.js:1:1043961)
    at h (41039.6d47c6ee08a5c558f08d.js:1:1044563)
    at d (f704fb87f8d9523e042e.js:1:9590)
    at ob (37248.e90e8800482fe6057ea8.js:1:781432)
    at u (37248.e90e8800482fe6057ea8.js:1:836642)
    at sN (37248.e90e8800482fe6057ea8.js:1:819658)
    at 37248.e90e8800482fe6057ea8.js:1:819524
    at sI (37248.e90e8800482fe6057ea8.js:1:819532)
    at sT (37248.e90e8800482fe6057ea8.js:1:816283)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by BerryGod1** [comment]
Okay

**Comment by Nuckyz** [comment]
Fixed in latest commits
