### ISSUE TITLE
[Bug] [Vencord's VoiceMessages plugin] Does not send when you click send (Uncaught TypeError: F8.CloudUpload is not a constructor)

### ISSUE THREAD

**Issue by jurassicjordan** [Vendicated/Vencord#2604]
### Discord Account

jurassicjordan

### What happens when the bug or crash occurs?

when attempting to upload an opus audio file to send via the VoiceMessages plugin, the file does not send when clicking the send button, the same result occurs when recording a voice messages, the send button does nothing, and the window stays open. 

### What is the expected behaviour?

VoiceMessages should send the audio clip I intend to send. 

### How do you recreate this bug or crash?

1 Enable the VoiceMessages plugin
2 get your file and convert it to opus (I used Audacity
2.5 or record your message
3 click send
4 the send button ignores you

### Errors

Uncaught TypeError: F8.CloudUpload is not a constructor
    at H8 (index.tsx:92:20)
    at onClick (index.tsx:238:25)
    at Object.eF (67096.60fb03d0b62c1fe1124f.js:12:930190)
    at eG (67096.60fb03d0b62c1fe1124f.js:12:930344)
    at 67096.60fb03d0b62c1fe1124f.js:12:948653
    at re (67096.60fb03d0b62c1fe1124f.js:12:948752)
    at rt (67096.60fb03d0b62c1fe1124f.js:12:949166)
    at 67096.60fb03d0b62c1fe1124f.js:12:954628
    at sA (67096.60fb03d0b62c1fe1124f.js:12:1011701)
    at eI (67096.60fb03d0b62c1fe1124f.js:12:929328)
H8 @ index.tsx:92
onClick @ index.tsx:238
eF @ 67096.60fb03d0b62c1fe1124f.js:12
eG @ 67096.60fb03d0b62c1fe1124f.js:12
(anonymous) @ 67096.60fb03d0b62c1fe1124f.js:12
re @ 67096.60fb03d0b62c1fe1124f.js:12
rt @ 67096.60fb03d0b62c1fe1124f.js:12
(anonymous) @ 67096.60fb03d0b62c1fe1124f.js:12
sA @ 67096.60fb03d0b62c1fe1124f.js:12
eI @ 67096.60fb03d0b62c1fe1124f.js:12
rs @ 67096.60fb03d0b62c1fe1124f.js:12
tF @ 67096.60fb03d0b62c1fe1124f.js:12
tP @ 67096.60fb03d0b62c1fe1124f.js:12

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by jurassicjordan** [comment]
closing issue, did not realize there was an update that fixes this. sorry for the disturbance
