### ISSUE TITLE
[Bug] InvisibleChat doesn't decrypt messages properly

### ISSUE THREAD

**Issue by WGrav01** [Vendicated/Vencord#2645]
### Discord Account

wgrav

### What happens when the bug or crash occurs?

When decrypting a message, the modal to enter the password works but just shows the "Made with ❤️ by c0dine and Sammy!" embed without the decrypted message.

### What is the expected behaviour?

InvisibleChat shows the decrypted message alongside the embed.

### How do you recreate this bug or crash?

1) Enable InvisibleChat (In this scenario I used Vesktop but my friend confirmed it wasn't working on the Windows discord client either)
2) Send a message with a 2 word (or more) cover and the password set to "password"
3) Press "Decrypt" enter the password (if prompted)
4) Note the embed appearing but the decrypted message not.

### Errors

```Logger.ts:40  Vencord   WebpackInterceptor  Patch by Vesktop had no effect (Module id is 292959): /\.isPlatformEmbedded(?=\?[A-Za-z_$][\w$]*\.DesktopNotificationTypes\.ALL)/g
_log @ Logger.ts:40
Logger.ts:40  Vencord   WebpackInterceptor  Patch by Vesktop had no effect (Module id is 649318): /"x-google-max-bitrate=".concat\([A-Za-z_$][\w$]*\)/
_log @ Logger.ts:40
web.d25f20b917981dc9b949.js:12 Window state not initialized undefined
f @ web.d25f20b917981dc9b949.js:12
noTrack.ts:113 Uncaught Error: Sentry successfully disabled
    at Function.set (noTrack.ts:118:23)
    at sentry.0d84f63558ce278f3270.js:26:646286
    at sentry.0d84f63558ce278f3270.js:26:647075
nocturnal.theme.css:1 ```
        
        
```       Failed to load resource: net::ERR_FILE_NOT_FOUND
web.d25f20b917981dc9b949.js:1 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at web.d25f20b917981dc9b949.js:1:10936
    at async Promise.all (index 3)
Logger.ts:40  Vencord   WebpackInterceptor  Patch by Vesktop had no effect (Module id is 897607): /([A-Za-z_$][\w$]*)\.default\.getState\(\).neverShowModal/
_log @ Logger.ts:40
web.d25f20b917981dc9b949.js:12 [DEPRECATED] Please use `subscribeWithSelector` middleware
a @ web.d25f20b917981dc9b949.js:12
web.d25f20b917981dc9b949.js:12 [GatewayZstdStore] Attempting to enable zstd but it is not supported
(anonymous) @ web.d25f20b917981dc9b949.js:12
Logger.ts:40  Vencord   VcNarrator  SpeechSynthesis not supported or no Narrator voices found. Thus, this plugin will not work. Check my Settings for more info
_log @ Logger.ts:40
42Third-party cookie will be blocked. Learn more in the Issues tab.
Unrecognized Content-Security-Policy directive 'prefetch-src'.
/channels/1167229967659188255/1207067008429203458:1 Unrecognized Content-Security-Policy directive 'prefetch-src'.
/channels/1167229967659188255/1207067008429203458:1 Access to fetch at 'https://pronoundb.org/api/v2/lookup?platform=discord&ids=578317601818542109%2C709871406376026135%2C985576431625076766%2C847677510610321408%2C905213712103768096' from origin 'https://discord.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pronoundb.org/api/v2/lookup?platform=discord&ids=578317601818542109%2C709871406376026135%2C985576431625076766%2C847677510610321408%2C905213712103768096:1 ```
        
        
```       Failed to load resource: net::ERR_FAILED
pronoundbUtils.ts:143 PronounDB fetching failed:  TypeError: Failed to fetch
    at t6 (pronoundbUtils.ts:129:27)
    at pronoundbUtils.ts:50:28
    at debounce.ts:30:38
t6 @ pronoundbUtils.ts:143
/api/v9/guilds/1221146430886903858/entitlements?with_sku=true&with_application=true&exclude_deleted=false:1 ```
        
        
 ```      Failed to load resource: the server responded with a status of 429 ()
/channels/1221146430886903858/1221149833700704408:1 Access to fetch at 'https://pronoundb.org/api/v2/lookup?platform=discord&ids=986685082830008331' from origin 'https://discord.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pronoundb.org/api/v2/lookup?platform=discord&ids=986685082830008331:1 ```
        
        
```       Failed to load resource: net::ERR_FAILED
pronoundbUtils.ts:143 PronounDB fetching failed:  TypeError: Failed to fetch
    at t6 (pronoundbUtils.ts:129:27)
    at pronoundbUtils.ts:50:28
    at debounce.ts:30:38
t6 @ pronoundbUtils.ts:143
images-ext-1.discordapp.net/external/TgrKaYCFdeuGBRG8uWk-7ZI4VDhcR8YNpf0eNsgtobQ/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1248405400831660103/1844ccdc67a7b526e7bdf7738f5c9069.webp?format=webp&width=96&height=96:1 ```
        
        
 ```      Failed to load resource: the server responded with a status of 404 ()
images-ext-1.discordapp.net/external/Dtmd_72QNhnZLgNt-1hjO_hrVN-SPD9gOc5jBZha0Js/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1241742834814554223/6ba88c3bda377e7ae7520e2f72830693.webp?format=webp&width=96&height=96:1 ```
        
        
```       Failed to load resource: the server responded with a status of 404 ()
images-ext-1.discordapp.net/external/Dtmd_72QNhnZLgNt-1hjO_hrVN-SPD9gOc5jBZha0Js/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1241742834814554223/6ba88c3bda377e7ae7520e2f72830693.webp?format=webp&width=96&height=96:1 ```
        
        
 ```      Failed to load resource: the server responded with a status of 404 ()
images-ext-1.discordapp.net/external/TgrKaYCFdeuGBRG8uWk-7ZI4VDhcR8YNpf0eNsgtobQ/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1248405400831660103/1844ccdc67a7b526e7bdf7738f5c9069.webp?format=webp&width=96&height=96:1 ```
        
        
```       Failed to load resource: the server responded with a status of 404 ()
images-ext-1.discordapp.net/external/TgrKaYCFdeuGBRG8uWk-7ZI4VDhcR8YNpf0eNsgtobQ/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1248405400831660103/1844ccdc67a7b526e7bdf7738f5c9069.webp?format=webp&width=96&height=96:1 ```
        
        
```       Failed to load resource: the server responded with a status of 404 ()
images-ext-1.discordapp.net/external/Dtmd_72QNhnZLgNt-1hjO_hrVN-SPD9gOc5jBZha0Js/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1241742834814554223/6ba88c3bda377e7ae7520e2f72830693.webp?format=webp&width=96&height=96:1 ```
        
        
```       Failed to load resource: the server responded with a status of 404 ()
images-ext-1.discordapp.net/external/TgrKaYCFdeuGBRG8uWk-7ZI4VDhcR8YNpf0eNsgtobQ/%3Fsize%3D128/https/cdn.discordapp.com/avatars/1248405400831660103/1844ccdc67a7b526e7bdf7738f5c9069.webp?format=webp&width=96&height=96:1 ```
        
        
  ```     Failed to load resource: the server responded with a status of 404 () ```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Realswitzer** [comment]
It's at least been broken since the Jun 18 Doomsday, and nothing is logged to the console during or after the decryption attempt. I don't know enough to confidently debug the script to find where the problem is. Using StegCloak in Node REPL decrypts the message as intended.
```
127 switzrr@switz-nyarch ~ % node
Welcome to Node.js v20.15.0.
Type ".help" for more information.
> const StegCloak = require('stegcloak');
undefined
> const stegcloak = new StegCloak(true, false);
undefined
> console.log(stegcloak.reveal("issue ⁣‍⁡⁡‌‌‍⁡⁤#2645 moment", "password"));
read if cute :3​
```
Additionally, in Vencord, with a password mismatch, no error is thrown and all it displays is the `Made with ❤️ by c0dine and Sammy!` embed.
