### ISSUE TITLE
[Bug] RPC is displayed incorrectly

### ISSUE THREAD

**Issue by r4v3b0yy** [Vendicated/Vencord#2861]
### Discord Account

r4v3_b0y

### What happens when the bug or crash occurs?

plugin does not display RPC completely

![1](https://github.com/user-attachments/assets/8b3068b8-addd-4000-a2d2-ad6a40887d55)
![2](https://github.com/user-attachments/assets/93bd8ffb-fd98-4c7c-91d4-751dc16c69c9)
![3](https://github.com/user-attachments/assets/d7223cf6-cc2d-4ea9-a150-d6620339a7f4)

### What is the expected behaviour?

The plugin should display RPC completely, lol

### How do you recreate this bug or crash?

I have no idea, at one point the plugin just stopped working.

### Errors

Oh no!
An error occurred while rendering this plugin's custom InfoComponent

TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Object.get (VencordRenderer:5:2680)
    at settingsAboutComponent (VencordRenderer:76:14910)
    at aA (web.b55432ea388bef878d66.js:12:990088)
    at sh (web.b55432ea388bef878d66.js:12:1001987)
    at l (web.b55432ea388bef878d66.js:12:1046221)
    at ok (web.b55432ea388bef878d66.js:12:1028319)
    at web.b55432ea388bef878d66.js:12:1028185
    at oG (web.b55432ea388bef878d66.js:12:1028193)
    at ov (web.b55432ea388bef878d66.js:12:1024944)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
use our support channel if you need support.
