### ISSUE TITLE
[Bug] Everytime I start sharing my screen, my microphone audio drops. Linux + Pipewire 

### ISSUE THREAD

**Issue by excited-bore** [Vendicated/Vencord#3016]
### What happens when the bug or crash occurs?

Everytime I start sharing my screen, my microphone audio drops.

### What is the expected behaviour?

System microhpone volume no change

### How do you recreate this bug or crash?

1. Install Linux
2. Install Pipewire (Pipewire-pulse, wireplumber and maybe of other pipewire libraries??)
3. Join vc
4. Share screen and notice that your systems microphone volume drops

### Errors

```
[UnifiedConnection(stream)] signalingState => have-local-offer
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC connected to media server: 35.214.167.77:50004
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Sending local SDP to RTC server.
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] iceGatheringState => gathering
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Remote media sink wants: {"any":100}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] updateVideoQuality: {
    "remoteSinkWantsPixelCount": 921600,
    "remoteSinkWantsMaxFramerate": 30,
    "encodingVideoMinBitRate": 500000,
    "encodingVideoMaxBitRate": 8000000,
    "encodingVideoBitRate": 600000,
    "streamParameters": [
        {
            "type": "video",
            "active": false,
            "rid": "100",
            "ssrc": 176547,
            "rtxSsrc": 176548,
            "quality": 100,
            "maxBitrate": 8000000,
            "maxFrameRate": 30,
            "maxResolution": {
                "type": "fixed",
                "width": 1280,
                "height": 720
            },
            "minBitrate": 500000,
            "targetBitrate": 600000,
            "maxPixelCount": 921600
        }
    ]
}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] BaseWebRTCConnection.updateVideoQuality: resolutionScaleFactor: 1, encodingVideoWidth: undefined, remoteSinkWantsMaxFramerate: 30, encodingVideoMaxBitRate: 8000000, localWant: 100
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Renegotiating: Codecs changed
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Setting media-session-id: 14883f65a532ece2b0b470071b62297b for rtc-connection-id: 25634257-6e48-4cf6-a994-3aefea01ade3
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] peerConnectionState => new
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] signalingState => stable
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] peerConnectionState => connecting
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Connection state change: CONNECTING => ICE_CHECKING
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC media connection state change: RTC_CONNECTING => ICE_CHECKING
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC connection state: RTC_CONNECTING => ICE_CHECKING
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] peerConnectionState => connecting
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Connection state change: ICE_CHECKING => DTLS_CONNECTING
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC media connection state change: ICE_CHECKING => DTLS_CONNECTING
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC connection state: ICE_CHECKING => DTLS_CONNECTING
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] iceGatheringState => complete
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] signalingState => have-local-offer
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] signalingState => stable
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] peerConnectionState => connected
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Connection state change: DTLS_CONNECTING => CONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC media connection state change: DTLS_CONNECTING => CONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC connection state: DTLS_CONNECTING => RTC_CONNECTED
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Renegotiating: Streams changed
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] updateVideoQuality: {
    "encodingVideoWidth": 1280,
    "encodingVideoHeight": 720,
    "encodingVideoFrameRate": 30,
    "captureVideoFrameRate": 30,
    "remoteSinkWantsMaxFramerate": 30,
    "remoteSinkWantsPixelCount": 921600,
    "encodingVideoBitRate": 600000,
    "encodingVideoMinBitRate": 500000,
    "encodingVideoMaxBitRate": 8000000,
    "streamParameters": [
        {
            "type": "video",
            "active": false,
            "rid": "100",
            "ssrc": 176547,
            "rtxSsrc": 176548,
            "quality": 100,
            "maxBitrate": 8000000,
            "maxFrameRate": 30,
            "maxResolution": {
                "type": "fixed",
                "width": 1280,
                "height": 720
            },
            "minBitrate": 500000,
            "targetBitrate": 600000,
            "maxPixelCount": 921600
        }
    ]
}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] BaseWebRTCConnection.updateVideoQuality: resolutionScaleFactor: 1, encodingVideoWidth: 1280, remoteSinkWantsMaxFramerate: 30, encodingVideoMaxBitRate: 8000000, localWant: 100
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] BaseWebRTCConnection.updateVideoQuality: old: undefined x undefined, new: 1280 x 720
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Remote media sink wants: {"any":100}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] updateVideoQuality: {
    "remoteSinkWantsPixelCount": 921600,
    "remoteSinkWantsMaxFramerate": 30,
    "encodingVideoMinBitRate": 500000,
    "encodingVideoMaxBitRate": 8000000,
    "encodingVideoBitRate": 600000,
    "streamParameters": [
        {
            "type": "video",
            "active": false,
            "rid": "100",
            "ssrc": 176547,
            "rtxSsrc": 176548,
            "quality": 100,
            "maxBitrate": 8000000,
            "maxFrameRate": 30,
            "maxResolution": {
                "type": "fixed",
                "width": 1280,
                "height": 720
            },
            "minBitrate": 500000,
            "targetBitrate": 600000,
            "maxPixelCount": 921600
        }
    ]
}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] BaseWebRTCConnection.updateVideoQuality: resolutionScaleFactor: 1, encodingVideoWidth: undefined, remoteSinkWantsMaxFramerate: 30, encodingVideoMaxBitRate: 8000000, localWant: 100
2web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] BaseWebRTCConnection.updateVideoQuality: old: 1280 x 720, new: undefined x undefined
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] signalingState => have-local-offer
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Sending heartbeat with last received sequence number: 1
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] signalingState => stable
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Remote media sink wants: {"any":100}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] updateVideoQuality: {
    "remoteSinkWantsPixelCount": 921600,
    "remoteSinkWantsMaxFramerate": 30,
    "encodingVideoMinBitRate": 500000,
    "encodingVideoMaxBitRate": 8000000,
    "encodingVideoBitRate": 600000,
    "streamParameters": [
        {
            "type": "video",
            "active": true,
            "rid": "100",
            "ssrc": 1777972314,
            "rtxSsrc": 3005058337,
            "quality": 100,
            "maxBitrate": 8000000,
            "maxFrameRate": 30,
            "maxResolution": {
                "type": "fixed",
                "width": 1280,
                "height": 720
            },
            "minBitrate": 500000,
            "targetBitrate": 600000,
            "maxPixelCount": 921600
        }
    ]
}
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] BaseWebRTCConnection.updateVideoQuality: resolutionScaleFactor: 1, encodingVideoWidth: undefined, remoteSinkWantsMaxFramerate: 30, encodingVideoMaxBitRate: 8000000, localWant: 100
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] Sending heartbeat with last received sequence number: 2
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Sending heartbeat with last received sequence number: 1
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] Sending heartbeat with last received sequence number: 2
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Sending heartbeat with last received sequence number: 1
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] Sending heartbeat with last received sequence number: 2
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Sending heartbeat with last received sequence number: 1
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] Heartbeat ACK received
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] [DISCONNECT] (true, 4006, Session is no longer valid.)
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
disconnect @ web.8cc22617123a6bf28c08.js:12
handleClose @ web.8cc22617123a6bf28c08.js:12
e.onclose @ web.8cc22617123a6bf28c08.js:12
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] Disconnected from RTC server, clean: true, code: 4006, reason: Session is no longer valid., state: RTC_CONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] Disconnect was not clean! reason=Session is no longer valid.. Reconnecting in 2.56 seconds.
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
_handleDisconnect @ web.8cc22617123a6bf28c08.js:12
a.emit @ web.8cc22617123a6bf28c08.js:1
emit @ web.8cc22617123a6bf28c08.js:12
disconnect @ web.8cc22617123a6bf28c08.js:12
handleClose @ web.8cc22617123a6bf28c08.js:12
e.onclose @ web.8cc22617123a6bf28c08.js:12
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(default)] Connection state change: CONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] RTC media connection state change: RTC_CONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] RTC connection state: RTC_CONNECTED => RTC_DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] RTC connection state: RTC_DISCONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] Error: getCodecSurvey is not implemented on MediaEngine of browsers.
    at C.getCodecSurvey (WebpackModule959856:2:6082)
    at es._handleDisconnect (web.8cc22617123a6bf28c08.js:12:2853508)
    at a.emit (web.8cc22617123a6bf28c08.js:1:1065560)
    at R.emit (web.8cc22617123a6bf28c08.js:12:8982153)
    at R.disconnect (web.8cc22617123a6bf28c08.js:12:2894556)
    at R.handleClose (web.8cc22617123a6bf28c08.js:12:2894033)
    at e.onclose (web.8cc22617123a6bf28c08.js:12:2891834)
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
Promise.catch (async)
_handleDisconnect @ web.8cc22617123a6bf28c08.js:12
a.emit @ web.8cc22617123a6bf28c08.js:1
emit @ web.8cc22617123a6bf28c08.js:12
disconnect @ web.8cc22617123a6bf28c08.js:12
handleClose @ web.8cc22617123a6bf28c08.js:12
e.onclose @ web.8cc22617123a6bf28c08.js:12
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] Destroy RTCConnection
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(default)] CLOSE
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] Disconnected from RTC server, clean: true, code: 1000, reason: Force Close, state: DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1305288373727924288, default)] RTC connection state: DISCONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Renegotiating: Streams changed
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] updateVideoQuality: {
    "encodingVideoWidth": 1280,
    "encodingVideoHeight": 720,
    "encodingVideoFrameRate": 30,
    "captureVideoFrameRate": 30,
    "remoteSinkWantsMaxFramerate": 30,
    "remoteSinkWantsPixelCount": 921600,
    "encodingVideoBitRate": 600000,
    "encodingVideoMinBitRate": 500000,
    "encodingVideoMaxBitRate": 8000000,
    "streamParameters": [
        {
            "type": "video",
            "active": true,
            "rid": "100",
            "ssrc": 1777972314,
            "rtxSsrc": 3005058337,
            "quality": 100,
            "maxBitrate": 8000000,
            "maxFrameRate": 30,
            "maxResolution": {
                "type": "fixed",
                "width": 1280,
                "height": 720
            },
            "minBitrate": 500000,
            "targetBitrate": 600000,
            "maxPixelCount": 921600
        }
    ]
}
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Destroy RTCConnection
web.8cc22617123a6bf28c08.js:12 [RTCControlSocket(stream)] CLOSE
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Disconnected from RTC server, clean: true, code: 1000, reason: Force Close, state: RTC_CONNECTED
web.8cc22617123a6bf28c08.js:12 [UnifiedConnection(stream)] Connection state change: CONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC media connection state change: RTC_CONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC connection state: RTC_CONNECTED => RTC_DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] RTC connection state: RTC_DISCONNECTED => DISCONNECTED
web.8cc22617123a6bf28c08.js:12 [RTCConnection(1306828403961495605, stream)] Error: getCodecSurvey is not implemented on MediaEngine of browsers.
    at C.getCodecSurvey (WebpackModule959856:2:6082)
    at O._handleDisconnect (web.8cc22617123a6bf28c08.js:12:2853508)
    at a.emit (web.8cc22617123a6bf28c08.js:1:1065560)
    at R.emit (web.8cc22617123a6bf28c08.js:12:8982153)
    at R.close (web.8cc22617123a6bf28c08.js:12:2898669)
    at O._cleanupSocket (web.8cc22617123a6bf28c08.js:12:2847623)
    at O.destroy (web.8cc22617123a6bf28c08.js:12:2843344)
    at O.destroy (web.8cc22617123a6bf28c08.js:12:4658386)
    at STREAM_DELETE (web.8cc22617123a6bf28c08.js:12:6974425)
    at StreamRTCConnectionStore_STREAM_DELETE (web.8cc22617123a6bf28c08.js:12:8090943)
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
Promise.catch (async)
_handleDisconnect @ web.8cc22617123a6bf28c08.js:12
a.emit @ web.8cc22617123a6bf28c08.js:1
emit @ web.8cc22617123a6bf28c08.js:12
close @ web.8cc22617123a6bf28c08.js:12
_cleanupSocket @ web.8cc22617123a6bf28c08.js:12
destroy @ web.8cc22617123a6bf28c08.js:12
destroy @ web.8cc22617123a6bf28c08.js:12
STREAM_DELETE @ web.8cc22617123a6bf28c08.js:12
StreamRTCConnectionStore_STREAM_DELETE @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
_dispatch @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
log @ web.8cc22617123a6bf28c08.js:12
_dispatchWithLogging @ web.8cc22617123a6bf28c08.js:12
_dispatchWithDevtools @ web.8cc22617123a6bf28c08.js:12
dispatch_STREAM_DELETE @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
flushWaitQueue @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
dispatch @ web.8cc22617123a6bf28c08.js:12
F @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
dispatchOne @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
batched @ web.8cc22617123a6bf28c08.js:12
dispatchMultiple @ web.8cc22617123a6bf28c08.js:12
I.flush @ web.8cc22617123a6bf28c08.js:12
_processWorkCallback @ web.8cc22617123a6bf28c08.js:12
_queueIdleCallback @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
setTimeout (async)
requestWorkTimeout @ web.8cc22617123a6bf28c08.js:12
scheduleFlush @ web.8cc22617123a6bf28c08.js:12
receiveDispatch @ web.8cc22617123a6bf28c08.js:12
_handleDispatch @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
handleFlushEnd @ web.8cc22617123a6bf28c08.js:12
d.push @ web.8cc22617123a6bf28c08.js:12
feed @ web.8cc22617123a6bf28c08.js:12
(anonymous) @ web.8cc22617123a6bf28c08.js:12
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
wrong repo (vesktop issue) and [duplicate](https://github.com/Vencord/Vesktop/issues?q=is%3Aissue+microphone+volume+is%3Aclosed+)
