### ISSUE TITLE
[Bug] When blocked users send many messages, NoBlockedUsers crashes discord

### ISSUE THREAD

**Issue by Currypan1229** [Vendicated/Vencord#3060]
### Discord Account

currypan1229

### What happens when the bug or crash occurs?

Show channels sent many messages by blocked users

### What is the expected behaviour?

Show other users messages

### How do you recreate this bug or crash?

1. block all users that are recently chatted
2. 2. Crash

### Errors

```
WebpackModule995340:2 Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at ob (WebpackModule995340:2:92855)
    at aW (WebpackModule995340:2:63921)
    at e.invalidate (web.408577dfa4ee1728159d.js:12:11008706)
    at web.408577dfa4ee1728159d.js:12:11009669
    at sG (WebpackModule995340:2:84279)
    at sX (WebpackModule995340:2:90672)
    at e (WebpackModule995340:2:111318)
    at e (WebpackModule995340:2:111214)
    at eval (WebpackModule995340:2:111329)
    at oG (WebpackModule995340:2:111841)
a9 @ WebpackModule995340:2
a.componentDidCatch.n.callback @ WebpackModule995340:2
iJ @ WebpackModule995340:2
sX @ WebpackModule995340:2
e @ WebpackModule995340:2
eval @ WebpackModule995340:2
oG @ WebpackModule995340:2
oR @ WebpackModule995340:2
r6 @ WebpackModule995340:2
eval @ WebpackModule995340:2
oG @ WebpackModule995340:2
oy @ WebpackModule995340:2
S @ web.408577dfa4ee1728159d.js:12
D @ web.408577dfa4ee1728159d.js:12
C.<computed> @ web.408577dfa4ee1728159d.js:1
O @ web.408577dfa4ee1728159d.js:1
L @ web.408577dfa4ee1728159d.js:1
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
simply don't do that

**Comment by Vendicated** [comment]
this is a stock discord issue.
