### ISSUE TITLE
[Bug] Youtube clips loading incorrectly when using YoutubeAdblock plugin

### ISSUE THREAD

**Issue by NorthLake** [Vendicated/Vencord#3063]
### Discord Account

northlake

### What happens when the bug or crash occurs?

When clicking play on an embed of a [Youtube clip](https://support.google.com/youtube/answer/10332730) the plugin will block the ad, but after that the entire video will be loaded instead of just the clip.
Note: the clip I've tried it with, is [this one](https://youtube.com/clip/UgkxXGppXD1QzYbZif1_o9udiYoT_LWSm-mz).

### What is the expected behaviour?

The ad is blocked and the clip is played

### How do you recreate this bug or crash?

1. Send a link to a Youtube clip
2. Click play on the embed

### Errors

Unsure if these are related to the bug, but they are logged as the clip/video is loaded
```
web.5136eb1709360a4c0ae8.js:12 Unrecognized Content-Security-Policy directive 'prefetch-src'.
e @ web.5136eb1709360a4c0ae8.js:12
e @ web.5136eb1709360a4c0ae8.js:12
e @ web.5136eb1709360a4c0ae8.js:12
e @ web.5136eb1709360a4c0ae8.js:12
sQ @ web.5136eb1709360a4c0ae8.js:12
sq @ web.5136eb1709360a4c0ae8.js:12
sz @ web.5136eb1709360a4c0ae8.js:12
sq @ web.5136eb1709360a4c0ae8.js:12
sz @ web.5136eb1709360a4c0ae8.js:12
[sq and sz alternating a LOT of times]
sz @ web.5136eb1709360a4c0ae8.js:12
sq @ web.5136eb1709360a4c0ae8.js:12
sz @ web.5136eb1709360a4c0ae8.js:12
sq @ web.5136eb1709360a4c0ae8.js:12
```
```
cast_sender.js:87 Uncaught SecurityError: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.
    at W.initialize (cast_sender.js:87:87)
    at chrome.cast.initialize (cast_sender.js:99:137)
    at g.k.init (remote.js:578:77)
    at zxb (remote.js:249:40)
    at pxb (remote.js:255:9)
    at d.disableCastApi.window.chrome.chrome.cast.chrome.cast.isAvailable.window.__onGCastApiAvailable (remote.js:243:402)
    at chrome.cast.da (cast_sender.js:101:297)
    at cast_sender.js:101:349
    at cast_sender.js:101:471
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by TheOnlyWayUp** [comment]
Can reproduce

**Comment by ioj4** [comment]
As far as I can tell this is just normal Discord behavior. There is probably no way to embed Youtube clips yet. If you look into the iframe, it's an url of the video embed (https://www.youtube.com/embed/skOHlrX_U5g), not the clip.

**Comment by ioj4** [comment]
nvm there does seem to be a way to embed clips, with: https://www.youtube.com/embed/skOHlrX_U5g?amp;clip=UgkxXGppXD1QzYbZif1_o9udiYoT_LWSm-mz&amp;clipt=EOyDJRjLryU

**Comment by NorthLake** [comment]
> As far as I can tell this is just normal Discord behavior.

I seriously remember watching a YouTube clip while not having the plugin active. Maybe it's déjà vu? Either way, clicking an embed without the plugin right now plays an ad, and then loads the entire video. Clicking play on the embed on the Android app (vanilla) does load the clip correctly, though. Maybe the fact that an ad plays is what screws it up? I'm not sure.
And even if Discord itself doesn't load clips correctly. Maybe it's something the plugin can fix?

**Comment by lolsuffocate** [comment]
This is just a stock Discord issue, it did work before. Timestamped links don't go to the timestamp in the embed anymore either

**Comment by xkalibratah** [comment]
By the way, vennie is a faggot with a shattering clitty. Everyone responded correctly

**Comment by Vendicated** [comment]
can't reproduce
