### ISSUE TITLE
[Bug] Card component no longer working

### ISSUE THREAD

**Issue by lewisakura** [Vendicated/Vencord#522]
### Discord Account

lewisakura#1337

### What happens when the bug or crash occurs?

The entire Discord client crashes due to the `Card` component not being found.

### What is the expected behaviour?

The `Card` component renders.

### How do you recreate this bug or crash?

1. Open Vencord settings or any other page with a Vencord-provided `Card`

### Errors

```
Error: Vencord could not find the Card Component
    at o (VencordWeb:12:248)
    at Sa (45eb806cdd178e4f93a2.js:1608:54)
    at yu (45eb806cdd178e4f93a2.js:1662:146)
    at Oc (45eb806cdd178e4f93a2.js:1655:89)
    at Ic (45eb806cdd178e4f93a2.js:1655:17)
    at hc (45eb806cdd178e4f93a2.js:1654:867)
    at ic (45eb806cdd178e4f93a2.js:1651:642)
    at uc (45eb806cdd178e4f93a2.js:1652:49)
    at Fo (45eb806cdd178e4f93a2.js:1591:577)
    at 45eb806cdd178e4f93a2.js:1649:555
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/af4c7d8a90cb8c943f082922798692af5be8578a
