### ISSUE TITLE
[Bug] Microphone not working

### ISSUE THREAD

**Issue by Botond0207** [Vendicated/Vencord#780]
### Discord Account

Botond0207#1935

### What happens when the bug or crash occurs?

Everyday i get a vencord update (i don't know if it's normal), i install it and restart discord. After this i can't talk in vc's, it's like i'm muted or my mic isn't recognized. I have to unplug my headset and plug it back in every single day to make it work. For the rest of the day i can restart my pc as many times i want and my mic will be fine so i think it's a problem related to vencord updates. I also have one plugin "VolumeBooster" enabled maybe that interferes with my microphone.

### What is the expected behaviour?

I expect Vencord to allow me to talk after updates without me reseating my headset's usb connector.

### How do you recreate this bug or crash?

1. Install a vencord update, Enable VolumeBooster plugin 
2. Restart discord
3. Join a vc
4. Try to talk

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by somerandomcloud** [comment]
Hey, the daily updates are normal, they actually happen more often than daily but whatever. These updates shouldn't interfere with your mic setup, and neither should VolumeBooster. Try posting your crash log though

**Comment by Botond0207** [comment]
Hello, thanks for the quick reply. I tried to avoid CTRL+SHIFT+I because there are some sketchy stuff over there and i don't want  to share it by accident, but if it's an error on my side and looking for console errors is necesarry i'll look for one.

**Comment by Botond0207** [comment]
> Hey, the daily updates are normal, they actually happen more often than daily but whatever. These updates shouldn't interfere with your mic setup, and neither should VolumeBooster. Try looking for any errors that are related in CTRL+SHIFT+I

I found one that says vencord at the end, here it is.

`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 5/13/2022 10:00 -0800, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://discord.com/assets/79d7e15ef9963457f52f.js:1443:330)
    at Bn (https://discord.com/assets/79d7e15ef9963457f52f.js:1469:696)
    at Wn (https://discord.com/assets/79d7e15ef9963457f52f.js:1472:356)
    at Zn (https://discord.com/assets/79d7e15ef9963457f52f.js:1472:199)
    at Yn (https://discord.com/assets/79d7e15ef9963457f52f.js:1471:886)
    at Kn (https://discord.com/assets/79d7e15ef9963457f52f.js:1472:697)
    at zn (https://discord.com/assets/79d7e15ef9963457f52f.js:1472:731)
    at i (https://discord.com/assets/79d7e15ef9963457f52f.js:1439:961)
    at 408481 (https://discord.com/assets/16f753cb4a2abd14f35b.js:21:346)
    at Object.o.<computed> (VencordRenderer:138:90)
r.<computed> @ 79d7e15ef9963457f52f.js:9288
`

**Comment by Vendicated** [comment]
discord issue. Just fully close discord instead of soft restarting
