### ISSUE TITLE
[Bug] Cannot load any vencord menus

### ISSUE THREAD

**Issue by OscarJohnsonn** [Vendicated/Vencord#782]
### Discord Account

O5ANGE#7161

### What happens when the bug or crash occurs?

![image](https://user-images.githubusercontent.com/98131096/229853255-668dfbf6-9b42-488a-91af-a2dcc9e42499.png)
The errors show canary but this also happens on stable

### What is the expected behaviour?

I expect discord to open the page and allow me to manage the plugins and themes

### How do you recreate this bug or crash?

It happens every time. probaly a me problem or conflicting plugins.

### Errors

```
93331fdd49b9fa249f99.js:9301 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at ai.<computed> [as get] (proxyLazy.ts:44:50)
    at index.tsx:73:32
    at Array.map (<anonymous>)
    at dv (index.tsx:71:43)
    at Sa (93331fdd49b9fa249f99.js:1744:54)
    at gu (93331fdd49b9fa249f99.js:1798:146)
    at Ic (93331fdd49b9fa249f99.js:1791:89)
    at mc (93331fdd49b9fa249f99.js:1791:17)
    at hc (93331fdd49b9fa249f99.js:1790:867)
r.<computed> @ 93331fdd49b9fa249f99.js:9301
93331fdd49b9fa249f99.js:9301  Vencord   React ErrorBoundary  A component threw an Error
 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at ai.<computed> [as get] (proxyLazy.ts:44:50)
    at index.tsx:73:32
    at Array.map (<anonymous>)
    at dv (index.tsx:71:43)
    at Sa (93331fdd49b9fa249f99.js:1744:54)
    at gu (93331fdd49b9fa249f99.js:1798:146)
    at Ic (93331fdd49b9fa249f99.js:1791:89)
    at mc (93331fdd49b9fa249f99.js:1791:17)
    at hc (93331fdd49b9fa249f99.js:1790:867)
r.<computed> @ 93331fdd49b9fa249f99.js:9301
93331fdd49b9fa249f99.js:9301  Vencord   React ErrorBoundary  Component Stack 
    at dv (VencordRenderer:77:7624)
    at <anonymous> (VencordRenderer:14:793)
    at xc (VencordRenderer:77:8090)
    at element
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2556:337)
    at ne (https://canary.discord.com/assets/bb904aa8b75e1f1ac840.js:36:27)
    at L (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9980:257)
    at div
    at eval (WebpackModule707961:2:176552)
    at L (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9980:257)
    at div
    at https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2773:439
    at div
    at div
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9699:79)
    at div
    at https://canary.discord.com/assets/93331fdd49b9fa249f99.js:143:878
    at P (https://canary.discord.com/assets/bb904aa8b75e1f1ac840.js:46:543)
    at n (https://canary.discord.com/assets/bb904aa8b75e1f1ac840.js:36:705)
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2556:337)
    at p (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:4874:24)
    at https://canary.discord.com/assets/93331fdd49b9fa249f99.js:4874:531
    at https://canary.discord.com/assets/dbdfdedeba5c337be9e6.js:1:637
    at p (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:4874:24)
    at https://canary.discord.com/assets/93331fdd49b9fa249f99.js:4874:531
    at https://canary.discord.com/assets/dbdfdedeba5c337be9e6.js:2:962
    at Suspense
    at Suspense(UserSettings)
    at div
    at l (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:259:570)
    at _ (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2708:482)
    at n (WebpackModule297406:2:1270958)
    at div
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9699:79)
    at n (WebpackModule297406:2:1273380)
    at Xle (WebpackModule297406:2:1274447)
    at div
    at n (WebpackModule707961:2:167454)
    at ece (WebpackModule297406:2:1274767)
    at t (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:1864:221)
    at t (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:1865:166)
    at i (WebpackModule297406:2:1323646)
    at Suspense
    at f
    at t (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:1864:221)
    at t (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:1865:166)
    at div
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2718:982)
    at VerificationLayerProvider
    at Pe (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2446:189)
    at div
    at div
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2718:982)
    at AppLayerProvider
    at p (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:4715:718)
    at L (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9980:257)
    at n (WebpackModule443269:2:4676)
    at O (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2477:909)
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2478:593)
    at a (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9140:533)
    at p (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2433:347)
    at zt (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2460:601)
    at n (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:3114:27)
    at a (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:9139:563)
    at https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2637:182
    at cn (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:2645:397)
    at t (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:1861:520)
    at t (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:1818:436)
    at br (https://canary.discord.com/assets/93331fdd49b9fa249f99.js:3151:523)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use stable

**Comment by schrmh** [comment]
I just got the same after trying to load a CSS that worked years ago on BetterDiscord. After that I restarted the Discord client and went back into Vencord and just got this (but .js files have a different name).
I was in fact using Canary but after seeing this issue I stable and get pretty much the same:

![image](https://user-images.githubusercontent.com/32062480/229880970-364e611e-2b62-460f-a772-de4e96ef2a7f.png)

**Comment by ItzOnlyAnimal** [comment]
yes just wait for the fix lmao
