### ISSUE TITLE
[Bug] Vencord stopped working after an update

### ISSUE THREAD

**Issue by lockieluke** [Vendicated/Vencord#783]
### What happens when the bug or crash occurs?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/25424409/229881326-b65a2ccb-d71b-42a7-a58c-75a395daba82.png">
Vencord is successfully installed however none of the menus work.  OpenASAR, on the other hand, remains working.  I have tried reinstalling both Discord and Vencord many times.

### What is the expected behaviour?

The menus should work

### How do you recreate this bug or crash?

1. Install Vencord using VencordInstaller on macOS
2. Open Discord and navigate to the settings menu
3. Go to one of the Vencord menus

### Errors

```
0192aa8c9176cfd4091d.js:9301 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at ai.<computed> [as get] (proxyLazy.ts:44:50)
    at index.tsx:73:32
    at Array.map (<anonymous>)
    at dv (index.tsx:71:43)
    at Sa (0192aa8c9176cfd4091d.js:1744:54)
    at gu (0192aa8c9176cfd4091d.js:1798:146)
    at Ic (0192aa8c9176cfd4091d.js:1791:89)
    at mc (0192aa8c9176cfd4091d.js:1791:17)
    at hc (0192aa8c9176cfd4091d.js:1790:867)
r.<computed> @ 0192aa8c9176cfd4091d.js:9301
0192aa8c9176cfd4091d.js:9301  Vencord   React ErrorBoundary  A component threw an Error
 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at ai.<computed> [as get] (proxyLazy.ts:44:50)
    at index.tsx:73:32
    at Array.map (<anonymous>)
    at dv (index.tsx:71:43)
    at Sa (0192aa8c9176cfd4091d.js:1744:54)
    at gu (0192aa8c9176cfd4091d.js:1798:146)
    at Ic (0192aa8c9176cfd4091d.js:1791:89)
    at mc (0192aa8c9176cfd4091d.js:1791:17)
    at hc (0192aa8c9176cfd4091d.js:1790:867)
r.<computed> @ 0192aa8c9176cfd4091d.js:9301
0192aa8c9176cfd4091d.js:9301  Vencord   React ErrorBoundary  Component Stack 
    at dv (VencordRenderer:77:7624)
    at <anonymous> (VencordRenderer:14:793)
    at xc (VencordRenderer:77:8090)
    at element
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:2556:337)
    at ne (https://discord.com/assets/6574f1a05476d1748fbb.js:36:27)
    at L (https://discord.com/assets/0192aa8c9176cfd4091d.js:9980:257)
    at div
    at https://discord.com/assets/0192aa8c9176cfd4091d.js:3044:48
    at L (https://discord.com/assets/0192aa8c9176cfd4091d.js:9980:257)
    at div
    at https://discord.com/assets/0192aa8c9176cfd4091d.js:2773:439
    at div
    at div
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:9699:79)
    at div
    at https://discord.com/assets/0192aa8c9176cfd4091d.js:143:878
    at P (https://discord.com/assets/6574f1a05476d1748fbb.js:46:543)
    at n (https://discord.com/assets/6574f1a05476d1748fbb.js:36:705)
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:2556:337)
    at p (https://discord.com/assets/0192aa8c9176cfd4091d.js:4874:24)
    at https://discord.com/assets/0192aa8c9176cfd4091d.js:4874:531
    at https://discord.com/assets/dbdfdedeba5c337be9e6.js:1:637
    at p (https://discord.com/assets/0192aa8c9176cfd4091d.js:4874:24)
    at https://discord.com/assets/0192aa8c9176cfd4091d.js:4874:531
    at https://discord.com/assets/dbdfdedeba5c337be9e6.js:2:962
    at Suspense
    at Suspense(UserSettings)
    at div
    at l (https://discord.com/assets/0192aa8c9176cfd4091d.js:259:570)
    at _ (https://discord.com/assets/0192aa8c9176cfd4091d.js:2708:482)
    at n (https://discord.com/assets/37201812fe393fa855a4.js:1345:809)
    at div
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:9699:79)
    at n (https://discord.com/assets/37201812fe393fa855a4.js:1348:250)
    at Xle (https://discord.com/assets/37201812fe393fa855a4.js:1349:323)
    at div
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:3034:767)
    at ece (https://discord.com/assets/37201812fe393fa855a4.js:1349:643)
    at t (https://discord.com/assets/0192aa8c9176cfd4091d.js:1864:221)
    at t (https://discord.com/assets/0192aa8c9176cfd4091d.js:1865:166)
    at i (https://discord.com/assets/37201812fe393fa855a4.js:1400:491)
    at Suspense
    at f
    at t (https://discord.com/assets/0192aa8c9176cfd4091d.js:1864:221)
    at t (https://discord.com/assets/0192aa8c9176cfd4091d.js:1865:166)
    at div
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:2718:982)
    at VerificationLayerProvider
    at xe (https://discord.com/assets/0192aa8c9176cfd4091d.js:2446:189)
    at div
    at div
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:2718:982)
    at AppLayerProvider
    at p (https://discord.com/assets/0192aa8c9176cfd4091d.js:4715:718)
    at L (https://discord.com/assets/0192aa8c9176cfd4091d.js:9980:257)
    at n (WebpackModule443269:2:4676)
    at O (https://discord.com/assets/0192aa8c9176cfd4091d.js:2477:909)
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:2478:593)
    at a (https://discord.com/assets/0192aa8c9176cfd4091d.js:9140:533)
    at p (https://discord.com/assets/0192aa8c9176cfd4091d.js:2433:347)
    at zt (https://discord.com/assets/0192aa8c9176cfd4091d.js:2460:601)
    at n (https://discord.com/assets/0192aa8c9176cfd4091d.js:3114:27)
    at a (https://discord.com/assets/0192aa8c9176cfd4091d.js:9139:563)
    at https://discord.com/assets/0192aa8c9176cfd4091d.js:2637:182
    at cn (https://discord.com/assets/0192aa8c9176cfd4091d.js:2645:397)
    at t (https://discord.com/assets/0192aa8c9176cfd4091d.js:1861:520)
    at t (https://discord.com/assets/0192aa8c9176cfd4091d.js:1818:436)
    at br (https://discord.com/assets/0192aa8c9176cfd4091d.js:3151:523)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by somerandomcloud** [comment]
Known issue, will be fixed asap

**Comment by Vendicated** [comment]
Yes we know. Please don't open issues for things like this
