### ISSUE TITLE
[Bug] Linux not working

### ISSUE THREAD

**Issue by craftpro100** [Vendicated/Vencord#787]
### What happens when the bug or crash occurs?

I updated the vencord client and this error came up 

### What is the expected behaviour?

I'd expect it to open plugins or an other vencord tab

### How do you recreate this bug or crash?

1. Update on Linux (console)
2. Open Vencord tab
3. Error

### Errors

```
Oh no!

An error occurred while rendering this Component. More info can be found below and in your console.

TypeError: Reflect.get called on non-object

at Reflect.get (<anonymous>) at Object.ai.<computed> [as get] (VencordRenderer:4:2629)
at (VencordRenderer:77:7946)
at Array.map (<anonymous>)
at dv (VencordRenderer:77:7987)
 at Sa (0192aa8c9176cfd4891d.js:1744:54)
at gu (0192aa8c9176cfd4091d.js:1798:145)
at Ic (0192aa8c9176cfd4891d.js:1791:89) at mc (0192aa8c9176cfd4091d.js:1791:17)
at hc (0197aa8c9176cfd4891d.js:1798:867)
```

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by cybrejon** [comment]
Can confirm I'm getting the same error on Linux, with Discord stable.

**Comment by epicacrylic** [comment]
This was happening on Windows as well, but it updated just as I went to write this and now it's working. But I did update, and reinstalled both Discord and Vencord and was still getting it until now
