### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ShiroYasha139** [Vendicated/Vencord#92]
Launched discord in the morning only to see the error

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/shiroe/Downloads/Vencord/dist/patcher.js'
Require stack:
- /opt/discord/resources/app/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/discord/resources/app/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

```

**Comment by ShiroYasha139** [comment]
Seems like I had deleted the Vencord folder, following install steps worked again.

**Comment by BanTheNons** [comment]
nice job
